.TH DUMPPNG "1" "MARCH 2025" "dumppng" "User Commands"
.SH NAME
dumppng \- dump PNG image files to C code
.SH SYNOPSIS
.B dumppng file.png  [ ... ]

.SH DESCRIPTION
.\" Add any additional description here
.PP
Generate C code from png image files for embedding images into C programs.
.\" .SH OPTIONS
.\" .TP
.\" \fB\-x, --xxxxx\fR
.\" This is not really an option, this is just a template for the man
.\" page for when the real options get implemented.
.SH EXAMPLE
.nf
$ ./dumppng star.png
struct png_file_bytes {
	int w, h, a;
	char *bytes;
};

static struct png_file_bytes star = {
	.w = 16,
	.h = 16,
	.a = 0,
	.bytes = {
		0x15, 0x13, 0x09, 0x12, 0x11, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xa2, 0x9a, 0x6a, 0x55, 0x50, 0x35, 0x00, 0x00, 0x00,
.fi
.PP
(many lines omitted)
.PP
.nf
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x30, 0x2c, 0x1a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00,
	},
};

.fi
.PP
.SH NOTES
This program is pretty rough and may not suit your needs at all.
.SH AUTHOR
Written by Stephen M. Cameron
.br
